# Generated by Django 5.2.1 on 2025-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('workshop', models.CharField(default='Tax Workshop on TARMS', max_length=150)),
                ('payment_method', models.CharField(default='bankTransfer', max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder', models.CharField(blank=True, max_length=100)),
                ('transaction_ref', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proof_of_payment', models.FileField(upload_to='proofs/')),
                ('terms', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
