# Generated by Django 5.2.1 on 2025-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
